### ISSUE TITLE
[question] prepare() and EOL

### ISSUE THREAD

**Issue by lgiordani** [yarrow/zet#2]
Hi! Thanks for the tool, very useful! Since I'm new to rust I have a question about `memchr`.
At https://github.com/yarrow/zet/blob/main/src/io.rs#L21 I understand that you want to detect if the first file contains either `\n` or `\r\n`.
* Why just the first file?
* Wouldn't it be possible to use `memmem::find_iter()` to simplify the logic?

Thanks a lot in advance. Sorry for opening an issue, I see discussions are not available.

**Comment by yarrow** [comment]
Thanks!

When Zet reads its input, it strips off the line terminator, which is either `\n` or `\r\n` (See [`src/io.rs` lines 165-173](https://github.com/yarrow/zet/blob/06679b8f031bbd69261bcb751acb4dcb4bc3e44d/src/io.rs#L165-L173))
And on output we need _some_ line ending — but should we use `\r\n` or `\n`?  Zet looks at the first line of the first file as a heuristic — _probably_ all files will use the same line terminator as the first file, and _probably_ the first line of the first file will have the same line terminator as the rest of the file.

Since `prepare` only cares about the first occurrence of a line terminator, an iterator like`memmem::find_iter()` isn't appropriate there. It might be a way of implementing  [`InputLines::next()`](https://github.com/yarrow/zet/blob/06679b8f031bbd69261bcb751acb4dcb4bc3e44d/src/io.rs#L153) — but I'm not sure how to do that! I used Andrew Gallant's [bstr](https://github.com/BurntSushi/bstr/blob/fffcb0ff62d8bebadefebbcbf20ae4460fa7a461/src/io.rs#L305) as a rough guide — as you know, they are the author of `memmem::find_iter()` and the rest of the `memchr` crate.  In the link, `find_byte` is a thin wrapper around `memchr` — after inlining, `buf.find_byte(terminator)` works out to `memchr(terminator, buf.as_bytes())`

Hope that answered your question!

**Comment by lgiordani** [comment]
It definitely make sense, thanks for the answer :+1:
